"""Add BucketLink table

Revision ID: ca8ffa4f827f
Revises: 9ed613fb03f0
Create Date: 2023-08-28 15:05:35.907937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8ffa4f827f'
down_revision = '9ed613fb03f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucket_links')
    # ### end Alembic commands ###
